language: java

cache:
  directories:
    - ~/.m2/repository

notifications:
  email:
    - ro.franchini@gmail.com

script:
  ./mvnw deploy -Pprod --quiet --settings .travis/settings.xml

jdk:
  - openjdk8
