language: java
env:
  global:
  - secure: MSSVQZ6h9QUHiJsy9d4sDdGQBj8UFRh9XtxMobiVHn1yL09TqupxBPuJHrxMJ5V3ViAr7RHuFd8n4FwcE27k4NWwM9XOTWBFrL2XUd4l9sL5OHT0oURyGrFelK8DltW3JFzwjs9HtdaGBDZ4vZFNKqCUDsimrsXQM9qZE8RNJgL+zoZjIF0ogrxGUNX+FOCoc3Umld+b8KoeMUvllvaQzQ75CrOsTQYRkWpb6Sea6Njq1OuGhNsPqbCJnjlY8AKnd6gBXcp/ToEXjFjKUUnlaTg3PNL7ad5KmdjmfQvoPyV2LAuks9fnwtTcaqp+nUsUu9ZueE/e355L52mFDDFaHKuWEgzDiBBZWPu5zo4CRgF2pCm2BjlXQBKC1LPK3PVxqncPRGO/exuW269aEUzEEtC7JvRXdv1FTKfyGT+usPpzH/2Na6gjwn9GC0FXkWtp9MQUSK2W6mv+O481LdrpHW+8ryUtpp3Z5Cwi9TwyLxqFS6LggaTIlgMYrhVbtyftr28wYHdw6tBzKPEnjp2cSRv71d2nrszOmzfZMyAskCYgG5NiBxRlwePah+TRT2Tq+61KPRfVO4O+DxHPqG6m+ayD61EuDqdBjJUT0z7oBbwa3buyAtIjYciHmfVTuxEorfJRe6ZwV3AYbcq3bwQs2AOvsPy4rQ7bafZFJoQdsiw=
  - secure: E0EM0rPL6ojSl6AtxZVS/nVcuG4OMgOiIwrC6zizzmKJSJtmeYx04dQrwgSlNNYpG/HESlxvJrd2kYYD/V1LY4mU+3O+2l8WX2KYIFQ7KYvXxHcvb6t9ov7TqJOc7ppv0K4mgelXSe8knu8iyE9iuGiljqfDxQlD5SRkRNTfN2LvFXpE/+kXtw2NcKPRkDRLEni+OCsGwJEvs10hFoM6nCNAPYDnp1FCd8RLszsp7BTg0PMFFIn7J8N9n2Zj6jXZs5+cOhK4ptI9wvd+zMAsBS1+kSYMEIhHgAV4FIju9qYkQS9GA9CChWnUynGeFj2VHLQspJaSYnzsaMTzKwUG2OkBABxeteuRXM5x6rxFDXyoy3x13+T73hM1qb5Kx+AzksZaDDd8wPaeAtQbxrIHM50XJcp/GlgAiWt8OQIXck68/b7XFwoNdUoRq67TW8V0KtYZNa3IpdaaAL3jcEu6TLcT7X22jCTcTsye0QOwOrIPd0Pe0U2/AdPMqcacpl7zcojjxqKU6uyemblch4QkH5O7Cxx/q4XDAuhR4AEUjF4Q2EYuaxGgT+vZj4nfSD2KubN+B+X+s7eqVDlUIPAePBxSMOnMBoSCnQPSc9VtWHI0gJvgtKhJHvUi3+LQRwdl6nrqiUQKzS4lUtlsFg4LfOijE0SBerIcllcbdy0W1Qk=

cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
  - ro.franchini@gmail.com
script: "./mvnw deploy --settings .travis/settings.xml"
jdk:
- openjdk8
