language: java
env:
  global:
    - secure: QDLRpYEF3e3HKVSIMrdtyWU+cMnvHsGoobDg0PcK4Dms2Zf+axPInviBCBCH61VgZWe/tJRh3CtDWC5jLvcV1YK6Etmi60Tv4pIQqurHrWE/0c8ZRYyjV9wwid5wVU24VKb75EU2nDb76JiFHXBVHGWv0e55EcLwEHneHNBE9NpEn4OCxWXwJxbc9U/6XN6lHc1jof4yV33h0//fWgDgO9nFYLNvqaDeDR5NoPbsHGv+zeeaqOBNQQptpN++OgQ5F5bg6x4HV/e0ti+b8gplZDo9VmrJtUGAj3xwfKGDRDwvEqU5UVUi3l4th9EAN3rYXT3lVdxqkGkhLO+MSv2cycAya8/O9fETqgvxCuoG9B6dU4L/HSYpkivwIefqiSc0TtQDlul5ufBBOO34kqESrZ2ABR9VO31PK+7rpi0bT0vxX6b1NMhbaug3z186L++tE3XmAEwMRN7rBaeZuNjnfTEThf5Fn+FT9akfTOAB05opDKVT2MWgaop+U26S+F1fB8qH69B/kfG1v23RI0+BfmbrDFxBEB7gTKIkxjSt2r6qg5b3OeWSd6IUsGL4vPw1SnoKQN/m1BVedrMlyiY5dhGWe+Ykg0XLgiOfKwNRpkcSzuZLAXjHbpFdMPnpe7L3JTT/Bu8BH3SsOgt/jXPw7rXvQMRCf7lxT6sMAoYgXI8=
    - secure: fnALlU8WunWDIgeVCZJusn4SbH2kyzoBY6UYYOQIeYGQ/efKwCAKcHXJtOSjtoN0yzoUJIXM1qE1b8Fl1FExZV704XvzjgieTN46LfDlirdatSXVL5EkKpmlRXX/vkEaYvJ7Zk1W/V8xwEv0tyZORzw9Nih8lMHZ+7ppPfe3y/jTX9+/fLoZxNAiqFlsFsncQJO6LVD5eYpSF9dLIfKV7Af5V8YOnhiihA2fBzHeFWqk/CSHLoQ9L1Q/NrXN1UijUG5aR6iTUz+YAoWY2kNiYFI0PKPwQQFyKHnP73FvNVOkWCq9EHmk0vl3R9OETTL49SxLi4a/TJOqSWp/3AuiHKUUEBT+ej2P0hd3Dn06Yv/LWQSIzpoVorcgOTq7MjYlzcFAh1d2t9xJFa4t7/CpG1/gtYybdpnwfHNZyoL7pyFEAWcf/YSVW07fsnPfhCk54VoIZzVxsuuWSxUZ17y9MSczpntBsbDrNZ6FeNNvPAe8qxe8dPY7fsJNXhN7/At/45tjrdejloYhxmprKpinfEhxHcd244hhO3WXis/bSmshtI5XU38JaAg6BFfEDX049hfRBeLXcjPQ0/mBuHNcMv9ZsB0m4VToNZkRI1Qxs8HLoGfU2Z2RNE3qHrhSreq0jnvm68BPF+RIhQRYwSgjxDtDU+3Jm77y4bOM/ZAHif0=

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - ro.franchini@gmail.com

script: "./mvnw deploy --settings .travis/settings.xml"

jdk:
  - openjdk8
