language: java

cache:
  directories:
    - ~/.m2/repository

notifications:
  email:
    - arcade@arcadeanalytics.com

script:
  ./mvnw deploy --quiet --settings .travis/settings.xml

jdk:
  - openjdk8
